### ISSUE TITLE
Integrity constraint violation issue on running reindex

### ISSUE THREAD

**Issue by syedsaleem086** [magento-hackathon/bestsellers-sorting-m2#1]
Hi,

I am facing Integrity constraint violation issue.
Here are the steps to reproduce the issue.
Magento2.2.2
PHP7.1

**Run the indexer command**
Magehackathon Bestseller indexer process unknown error:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`kegking`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CA), query was: INSERT INTO `catalog_product_entity_varchar` (`attribute_id`,`store_id`,`entity_id`,`value`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)

**Comment by amelojunior** [comment]
@syedsaleem086 At first this error is caused by deleted products.
One simple try catch at:
**Model/SimpleProductsAggregatedReportDataProcessor.php**
OR delete old orders containing these deleted products, may resolve this problem

**Comment by amelojunior** [comment]
@syedsaleem086 

I have the same problem. I have identified that the cause of this is the deleted products.
One option would be to delete these orders with deleted products
OR
Override de bestsellers native query here:
vendor/magento/module-sales/Model/ResourceModel/Report/Bestsellers.php near line 151
inserting that:
)->joinInner(
                ['product' => $this->getTable('catalog_product_entity')],
                'order_item.product_id = product.entity_id',
                []

*I'm applying this solution now, so I still do not know if it can cause any consequences, I believe not, except for the need to review the next magento updates, just like any overwritten code

**Comment by amelojunior** [comment]
*this extension only works with simple products

**Comment by rohit-prjpt** [comment]
we can just exclude items which are no more exists from inserting using following code:
`namespace MagentoHackathon\BestsellersSorting\Model;

class SimpleProductsAggregatedReportDataProcessor
{


    /**
     * @var ResourceModel\Bestseller
     */
    private $bestseller;
    /**
     * @var \Magento\Catalog\Model\ResourceModel\Product\Action
     */
    private $action;
    /**
     * @var ResourceModel\Bestseller\Collection
     */
    private $collection;

    protected $_productCollectionFactory;
    
    public function __construct(
        \MagentoHackathon\BestsellersSorting\Model\ResourceModel\Bestseller $bestseller,
        \Magento\Catalog\Model\ResourceModel\Product\Action $action,
        \MagentoHackathon\BestsellersSorting\Model\ResourceModel\Bestseller\Collection $collection,
    	\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory
    )
    {

        $this->bestseller = $bestseller;
        $this->action = $action;
        $this->collection = $collection;
        $this->_productCollectionFactory = $productCollectionFactory;
    }

    public function calculate($storeId = 0)
    {
        $this->bestseller->aggregate(null, null);
		
        $productIds = $this->_productCollectionFactory->create()->getAllIds();
        
        $collection = $this->collection;
        /** @var \MagentoHackathon\BestsellersSorting\Model\Bestseller $productId */
        foreach ($collection as $item) {

        	/**
        	 * https://github.com/magento-hackathon/bestsellers-sorting-m2/issues/1
        	 *  Integrity constraint violation issue on running reindex #1
        	 */
        	if(!in_array($item->getProductId(),$productIds)) {
        		continue;
        	}
        	
            /**https://magento.stackexchange.com/questions/151186/best-way-to-update-products-attribute-value */
            $this->action->updateAttributes(
                [$item->getProductId()],
                ['bestseller_order' => $item->getRatingPos()],
                $item->getStoreId());
        }


    }
}`

That's all.
